import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";
import NavBar from "./Component/NavBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "GK-GS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>

      <Script src="https://kit.fontawesome.com/9fa326583e.js" crossOrigin="anonymous"></Script>

    </html>
  );
}
